### ISSUE TITLE
Current master is completely busted

### ISSUE THREAD

**Issue by tterribe** [cisco/thor#31]
Tested with https://media.xiph.org/video/derf/y4m/coastguard_qcif.y4m

Second frame from the decoder:
![Second frame from the decoder](https://people.xiph.org/~tterribe/thor/cg0002-busted.png)

Second frame reconstruction from the encoder:
![Second frame reconstruction from the encoder](https://people.xiph.org/~tterribe/thor/cg0002-rec-busted.png)

Frame 289 from the decoder:
![Frame 289 from the decoder](https://people.xiph.org/~tterribe/thor/cg0289-busted.png)

Frame 289 reconstruction from the encoder:
![Second frame reconstruction from the encoder](https://people.xiph.org/~tterribe/thor/cg0289-rec-busted.png)

Disabling B-frames makes the green and purple streaks go away, but the color drift mismatch between encoder and decoder remains.

**Comment by thdav** [comment]
Should be fixed in latest master.
